### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by cassinius** [cassinius/trpc-cluster#1]
## Todos

- [ ] write some 
- [ ] try to scale it to a multi-node cluster via PM2
   - if it works, fine !
- [ ] install Redis & replace the simple Node.js EventEmitter mechanism with a redis pub/sub-by thing
- [ ] start up 2 local instances on different ports & configure an nginx load balancer with sticky sessions
- [ ] start up 2 hetzner cloud instances & put a load balancer with sticky sessions between them

## Documentation
